import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0f1b14',
  },
  root: {
    flex: 1,
    backgroundColor: '#0f1b14',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#c9d2cc',
  },
  brand: {
    color: '#f3f7f4',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    marginLeft: 12,
    flex: 1,
  },
  headerIcons: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon: {
    fontSize: 16,
    color: '#e6f4ea',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 120,
  },
  heroCard: {
    backgroundColor: '#132016',
    borderRadius: 28,
    paddingVertical: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 18,
    elevation: 4,
  },
  ringWrap: {
    width: 200,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringCenter: {
    position: 'absolute',
    alignItems: 'center',
  },
  ringLabel: {
    color: '#7aa084',
    fontSize: 12,
    letterSpacing: 1.2,
  },
  ringValue: {
    color: '#f2f6f3',
    fontSize: 36,
    fontWeight: '700',
    fontFamily: 'Poppins-SemiBold',
    marginTop: 4,
  },
  ringSub: {
    color: '#9ab2a1',
    fontSize: 12,
    marginTop: 4,
  },
  ringTrack: {
    stroke: '#1f3325',
  },
  ringProgress: {
    stroke: '#7cff7c',
  },
  pill: {
    marginTop: 18,
    backgroundColor: '#0f2c18',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
  },
  pillDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#7cff7c',
    marginRight: 8,
  },
  pillText: {
    color: '#9fe6a6',
    fontSize: 12,
    letterSpacing: 0.8,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
  },
  featureCard: {
    marginTop: 18,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#203624',
    height: 140,
  },
  featureImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  featureOverlay: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(10, 20, 12, 0.55)',
  },
  featureContent: {
    padding: 16,
  },
  featureLabel: {
    color: '#9fc8a6',
    fontSize: 12,
    letterSpacing: 0.8,
  },
  featureValue: {
    color: '#f4fff6',
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Poppins-SemiBold',
    marginTop: 6,
  },
  featureSub: {
    color: '#c7dfce',
    fontSize: 12,
    marginTop: 4,
  },
  featureAction: {
    position: 'absolute',
    right: 14,
    bottom: 14,
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#80f489',
    alignItems: 'center',
    justifyContent: 'center',
  },
  featureActionText: {
    color: '#0b1c11',
    fontSize: 22,
    fontWeight: '700',
  },
  sectionTitle: {
    marginTop: 18,
    color: '#f2f6f3',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
  },
  listItem: {
    backgroundColor: '#132016',
    borderRadius: 18,
    padding: 14,
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  listIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#1d2f22',
    alignItems: 'center',
    justifyContent: 'center',
  },
  listIconText: {
    fontSize: 18,
    color: '#7cff7c',
  },
  listText: {
    flex: 1,
    marginLeft: 12,
  },
  listTitle: {
    color: '#f3f7f4',
    fontSize: 15,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
  },
  listSubtitle: {
    color: '#96aa9d',
    fontSize: 12,
    marginTop: 2,
  },
  listChevron: {
    color: '#7cff7c',
    fontSize: 24,
  },
  miniList: {
    marginTop: 10,
    backgroundColor: '#132016',
    borderRadius: 16,
    padding: 12,
  },
  miniHeader: {
    marginBottom: 6,
  },
  miniTitle: {
    color: '#9fb2a6',
    fontSize: 12,
  },
  miniRow: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#1e2c23',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  miniText: {
    flex: 1,
    marginRight: 10,
  },
  miniName: {
    color: '#f3f7f4',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
  },
  miniPkg: {
    color: '#7aa084',
    fontSize: 11,
    marginTop: 2,
  },
  accessCard: {
    backgroundColor: '#14261a',
    borderRadius: 16,
    padding: 14,
    marginTop: 8,
  },
  accessTitle: {
    color: '#f2f6f3',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
  },
  accessSub: {
    color: '#9fb2a6',
    fontSize: 12,
    marginTop: 4,
  },
  accessButton: {
    marginTop: 10,
    alignSelf: 'flex-start',
    backgroundColor: '#80f489',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  accessButtonText: {
    color: '#0b1c11',
    fontSize: 12,
    fontWeight: '700',
  },
  appsCard: {
    marginTop: 14,
    backgroundColor: '#132016',
    borderRadius: 16,
    padding: 12,
  },
  statsCard: {
    marginTop: 14,
    backgroundColor: '#132016',
    borderRadius: 16,
    padding: 14,
  },
  appsHeader: {
    marginBottom: 6,
  },
  appRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#1e2c23',
    flexDirection: 'row',
    alignItems: 'center',
  },
  appRight: {
    alignItems: 'flex-end',
  },
  appIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#1d2f22',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  appIcon: {
    width: 28,
    height: 28,
    borderRadius: 6,
  },
  appIconFallback: {
    width: 18,
    height: 18,
    borderRadius: 4,
    backgroundColor: '#2b3c30',
  },
  appText: {
    flex: 1,
    marginRight: 12,
  },
  appName: {
    color: '#f3f7f4',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
  },
  appPkg: {
    color: '#7aa084',
    fontSize: 11,
    marginTop: 2,
  },
  appSize: {
    color: '#9fe6a6',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
  },
  appUninstallButton: {
    marginTop: 6,
    backgroundColor: '#1e2c23',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
  },
  appUninstallText: {
    color: '#ffb5b5',
    fontSize: 10,
    fontWeight: '600',
  },
});
