import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_W } = Dimensions.get('window');
const CARD_GAP = 12;
const TILE_W = (SCREEN_W - 40 - CARD_GAP) / 2;

export const colors = {
  bg: '#0b1410',
  card: '#12201a',
  cardLight: '#182a21',
  border: '#1e3328',
  accent: '#5ceb6b',
  accentDim: '#2b5e33',
  accentBg: 'rgba(92, 235, 107, 0.08)',
  text: '#f0f5f1',
  textSec: '#8fa898',
  textDim: '#627a6b',
  danger: '#ff6b6b',
  dangerBg: 'rgba(255, 107, 107, 0.12)',
  dangerDim: '#5c2a2a',
  warn: '#ffc95c',
  white: '#ffffff',
};

export const fonts = {
  regular: 'Poppins-Regular',
  semiBold: 'Poppins-SemiBold',
  bold: 'Poppins-Bold',
};

export const styles = StyleSheet.create({
  // ─── Layout ───
  safeArea: { flex: 1, backgroundColor: colors.bg },
  root: { flex: 1, backgroundColor: colors.bg },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 120 },

  // ─── Header ───
  header: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.accentDim,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brand: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
    fontFamily: fonts.semiBold,
    marginLeft: 12,
    flex: 1,
  },
  headerIcons: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon: { fontSize: 16, color: colors.textSec },

  // ─── Hero / Storage Ring ───
  heroCard: {
    backgroundColor: colors.card,
    borderRadius: 28,
    paddingVertical: 28,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  ringWrap: {
    width: 200,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringCenter: { position: 'absolute', alignItems: 'center' },
  ringLabel: {
    color: colors.textDim,
    fontSize: 11,
    letterSpacing: 1.5,
    fontFamily: fonts.semiBold,
  },
  ringValue: {
    color: colors.text,
    fontSize: 38,
    fontWeight: '700',
    fontFamily: fonts.bold,
    marginTop: 2,
  },
  ringSub: {
    color: colors.textSec,
    fontSize: 13,
    fontFamily: fonts.regular,
    marginTop: 2,
  },
  ringTrack: { stroke: colors.border },
  ringProgress: { stroke: colors.accent },
  pill: {
    marginTop: 18,
    backgroundColor: colors.accentBg,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.accentDim,
  },
  pillDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.accent,
    marginRight: 8,
  },
  pillText: {
    color: colors.accent,
    fontSize: 11,
    letterSpacing: 0.8,
    fontWeight: '600',
    fontFamily: fonts.semiBold,
  },

  // ─── Feature Card (CO2) ───
  featureCard: {
    marginTop: 16,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: colors.cardLight,
    height: 130,
    borderWidth: 1,
    borderColor: colors.border,
  },
  featureImage: { position: 'absolute', width: '100%', height: '100%' },
  featureOverlay: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(11, 20, 16, 0.65)',
  },
  featureContent: { padding: 18, flex: 1, justifyContent: 'center' },
  featureLabel: {
    color: colors.textDim,
    fontSize: 11,
    letterSpacing: 1.2,
    fontFamily: fonts.semiBold,
  },
  featureValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '700',
    fontFamily: fonts.semiBold,
    marginTop: 4,
  },
  featureSub: {
    color: colors.textSec,
    fontSize: 12,
    fontFamily: fonts.regular,
    marginTop: 4,
  },
  featureAction: {
    position: 'absolute',
    right: 14,
    bottom: 14,
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  featureActionText: { color: colors.bg, fontSize: 22, fontWeight: '700' },

  // ─── Section ───
  sectionTitle: {
    marginTop: 20,
    marginBottom: 4,
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
    fontFamily: fonts.semiBold,
  },

  // ─── List Items ───
  listItem: {
    backgroundColor: colors.card,
    borderRadius: 18,
    padding: 14,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  listIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: colors.accentBg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.accentDim,
  },
  listIconText: { fontSize: 20, color: colors.accent },
  listText: { flex: 1, marginLeft: 14 },
  listTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '600',
    fontFamily: fonts.semiBold,
  },
  listSubtitle: {
    color: colors.textSec,
    fontSize: 12,
    fontFamily: fonts.regular,
    marginTop: 2,
  },
  listChevron: { color: colors.accent, fontSize: 22 },

  // ─── Tiles (CleanerHome) ───
  tileContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: CARD_GAP,
    marginTop: 12,
  },
  tile: {
    width: TILE_W,
    backgroundColor: colors.card,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 120,
    justifyContent: 'space-between',
  },
  tileIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  tileTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
    fontFamily: fonts.semiBold,
    marginTop: 4,
  },
  tileSub: {
    color: colors.textSec,
    fontSize: 11,
    fontFamily: fonts.regular,
    marginTop: 2,
  },

  // ─── Mini Lists ───
  miniList: {
    marginTop: 10,
    backgroundColor: colors.card,
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  miniHeader: { marginBottom: 8 },
  miniTitle: {
    color: colors.textSec,
    fontSize: 12,
    fontFamily: fonts.semiBold,
  },
  miniRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
  },
  miniText: { flex: 1, marginLeft: 8 },
  miniName: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
    fontFamily: fonts.semiBold,
  },
  miniPkg: {
    color: colors.textDim,
    fontSize: 11,
    fontFamily: fonts.regular,
    marginTop: 1,
  },

  // ─── Access / Permission Card ───
  accessCard: {
    backgroundColor: colors.card,
    borderRadius: 20,
    padding: 20,
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  accessTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
    fontFamily: fonts.semiBold,
    textAlign: 'center',
  },
  accessSub: {
    color: colors.textSec,
    fontSize: 13,
    fontFamily: fonts.regular,
    marginTop: 8,
    textAlign: 'center',
    lineHeight: 20,
  },
  accessButton: {
    marginTop: 14,
    backgroundColor: colors.accent,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 14,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  accessButtonText: {
    color: colors.bg,
    fontSize: 14,
    fontWeight: '700',
    fontFamily: fonts.semiBold,
  },

  // ─── Stats Card ───
  statsCard: {
    marginTop: 12,
    backgroundColor: colors.card,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  statLabel: {
    color: colors.textSec,
    fontSize: 13,
    fontFamily: fonts.regular,
    flex: 1,
  },
  statValue: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '600',
    fontFamily: fonts.semiBold,
  },
  statBigValue: {
    color: colors.accent,
    fontSize: 28,
    fontWeight: '700',
    fontFamily: fonts.bold,
  },

  // ─── Apps Screen ───
  appsCard: {
    marginTop: 12,
    backgroundColor: colors.card,
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  appsHeader: { marginBottom: 8 },
  appRow: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
  },
  appRight: { alignItems: 'flex-end' },
  appIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.cardLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    overflow: 'hidden',
  },
  appIcon: { width: 32, height: 32, borderRadius: 8 },
  appIconFallback: {
    width: 20,
    height: 20,
    borderRadius: 6,
    backgroundColor: colors.border,
  },
  appText: { flex: 1, marginRight: 12 },
  appName: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
    fontFamily: fonts.semiBold,
  },
  appPkg: {
    color: colors.textDim,
    fontSize: 11,
    fontFamily: fonts.regular,
    marginTop: 1,
  },
  appSize: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: '600',
    fontFamily: fonts.semiBold,
  },
  appUninstallButton: {
    marginTop: 6,
    backgroundColor: colors.dangerBg,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.dangerDim,
  },
  appUninstallText: {
    color: colors.danger,
    fontSize: 11,
    fontWeight: '600',
    fontFamily: fonts.semiBold,
  },

  // ─── Cleaner List ───
  scanButton: {
    backgroundColor: colors.accent,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  scanButtonText: {
    color: colors.bg,
    fontSize: 15,
    fontWeight: '700',
    fontFamily: fonts.semiBold,
  },
  summaryBar: {
    backgroundColor: colors.card,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  fileCard: {
    backgroundColor: colors.card,
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  checkboxChecked: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  groupCard: {
    backgroundColor: colors.card,
    borderRadius: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  groupHeader: {
    backgroundColor: colors.cardLight,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  groupTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '600',
    fontFamily: fonts.semiBold,
  },
  groupSub: {
    color: colors.textSec,
    fontSize: 11,
    fontFamily: fonts.regular,
  },
  keepBadge: {
    backgroundColor: colors.accentBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.accentDim,
  },
  keepBadgeText: {
    color: colors.accent,
    fontSize: 10,
    fontWeight: '600',
    fontFamily: fonts.semiBold,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.card,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    flexDirection: 'row',
    gap: 10,
  },
  bottomBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  bottomBtnDelete: { backgroundColor: colors.danger },
  bottomBtnRestore: { backgroundColor: colors.accentDim },
  bottomBtnText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '700',
    fontFamily: fonts.semiBold,
  },

  // ─── Empty state ───
  emptyState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    color: colors.textSec,
    fontSize: 14,
    fontFamily: fonts.regular,
    marginTop: 12,
    textAlign: 'center',
  },
});
